apiVersion: v1
kind: ConfigMap
metadata:
  name: heart-disease-api-config
  namespace: heart-disease
data:
  API_HOST: "0.0.0.0"
  API_PORT: "8080"
  MODEL_PATH: "/app/models/heart_disease_model.pkl"
  LOG_LEVEL: "INFO"
